// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniMateBackend.Data;

#nullable disable

namespace UniMateAI.Api.Migrations
{
    [DbContext(typeof(UniMateDbContext))]
    [Migration("20260912110310_AcademicRecords")]
    partial class AcademicRecords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcademicSemesterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("GradePoint")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsLab")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetake")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousGrade")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcademicSemesterId");

                    b.ToTable("AcademicCourses");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicSemester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdditionalFeeComments")
                        .HasColumnType("TEXT");

                    b.Property<double?>("CGPA")
                        .HasColumnType("REAL");

                    b.Property<decimal>("FeeReceived")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FeeRemaining")
                        .HasColumnType("TEXT");

                    b.Property<double?>("GPA")
                        .HasColumnType("REAL");

                    b.Property<string>("PaymentComments")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousOutstanding")
                        .HasColumnType("TEXT");

                    b.Property<string>("RebateComments")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RebateOrConcession")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SemesterFee")
                        .HasColumnType("TEXT");

                    b.Property<string>("SemesterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Session")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalOutstanding")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "Session")
                        .IsUnique();

                    b.ToTable("AcademicSemesters");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.CourseAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcademicCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxMarks")
                        .HasColumnType("REAL");

                    b.Property<double>("ObtainedMarks")
                        .HasColumnType("REAL");

                    b.Property<double>("Weightage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AcademicCourseId");

                    b.ToTable("CourseAssessments");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.CourseAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcademicCourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AttendanceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcademicCourseId");

                    b.ToTable("CourseAttendanceRecords");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.CurriculumCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditHours")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLab")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SemesterNumber", "CourseId")
                        .IsUnique();

                    b.ToTable("CurriculumCourses");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CGPA")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Semester")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UniversityEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.HasIndex("UniversityEmail")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicCourse", b =>
                {
                    b.HasOne("UniMateAI.Api.Models.AcademicSemester", "AcademicSemester")
                        .WithMany("Courses")
                        .HasForeignKey("AcademicSemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicSemester");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicSemester", b =>
                {
                    b.HasOne("UniMateAI.Api.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.CourseAssessment", b =>
                {
                    b.HasOne("UniMateAI.Api.Models.AcademicCourse", "AcademicCourse")
                        .WithMany("Assessments")
                        .HasForeignKey("AcademicCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicCourse");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.CourseAttendance", b =>
                {
                    b.HasOne("UniMateAI.Api.Models.AcademicCourse", "AcademicCourse")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AcademicCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicCourse");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicCourse", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("AttendanceRecords");
                });

            modelBuilder.Entity("UniMateAI.Api.Models.AcademicSemester", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
